name: 'runcache'
description: 'cache run results'
author: 'qawatake'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# branding:
#   icon: 'heart'
#   color: 'red'

# Define your inputs here.
inputs:
  path:
    description: 'Used to specify the path to the cache'
    required: true
  skip-save:
    description: 'Used to specify whether to skip saving the cache'
    required: true
  github-token:
    description: 'Used to delete cache'
    required: true
  save-on-failure:
    description: 'Used to specify whether to save the cache on failure'
    required: false
    default: 'false'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/main/index.js
  post: dist/post/index.js
  post-if:
    '!github.event.inputs.skip-save && (success() ||
    github.event.inputs.save-on-failure)'
